### ISSUE TITLE
Cannot run on Termux

### ISSUE THREAD

**Issue by wmyfelix** [RanKKI/Bangumi#10]
~/scripts/Bangumi $ uvicorn main:app --host 0.0.0.0 --log-config conf/log.yml
2022-09-25 19:56:27 - [INFO] - Aria2 Connecting to http://127.0.0.1:6800
2022-09-25 19:56:27 - [INFO] - Started server process [31025]
2022-09-25 19:56:27 - [INFO] - Waiting for application startup.
2022-09-25 19:56:27 - [INFO] - Connecting to Redis...
2022-09-25 19:56:27 - [INFO] - Connected to Redis, version 6.2.7
2022-09-25 19:56:27 - [INFO] - Connected to aria2: 1.36.0
2022-09-25 19:56:27 - [INFO] - Starting...
2022-09-25 19:56:27 - [INFO] - Application startup complete.
2022-09-25 19:56:27 - [INFO] - Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
2022-09-25 19:56:27 - [INFO] - Env
Exception in thread Thread-2:
Traceback (most recent call last):
2022-09-25 19:56:27 - [INFO] - -----------  --------------------------------------------------
2022-09-25 19:56:27 - [INFO] - Log Level    INFO
2022-09-25 19:56:27 - [INFO] - Client       aria2
2022-09-25 19:56:27 - [INFO] - Client Addr  :wmy20050309@127.0.0.1:6800
2022-09-25 19:56:27 - [INFO] - Redis        @127.0.0.1:6379
2022-09-25 19:56:27 - [INFO] - Check        600
2022-09-25 19:56:27 - [INFO] - Download     /data/data/com.termux/files/home/storage/downloads
2022-09-25 19:56:27 - [INFO] - Cache        ./.cache
2022-09-25 19:56:27 - [INFO] - Media        /data/data/com.termux/files/home/media
2022-09-25 19:56:27 - [INFO] - Config       ./.config
2022-09-25 19:56:27 - [INFO] - Seeding      False
2022-09-25 19:56:27 - [INFO] - 
  File "/data/data/com.termux/files/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/data/data/com.termux/files/home/scripts/Bangumi/./bangumi/manager/config.py", line 33, in run
    self.observer.start()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/watchdog/observers/api.py", line 262, in start
    emitter.start()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/watchdog/utils/__init__.py", line 93, in start
    self.on_thread_start()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/watchdog/observers/inotify.py", line 118, in on_thread_start
    self._inotify = InotifyBuffer(path, self.watch.is_recursive)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__
    self._inotify = Inotify(path, recursive)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 169, in __init__
    self._add_watch(path, event_mask)
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 386, in _add_watch
    Inotify._raise_error()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/watchdog/observers/inotify_c.py", line 406, in _raise_error
    raise OSError(err, os.strerror(err))
FileNotFoundError: [Errno 2] No such file or directory

**Comment by RanKKI** [comment]
Okay, I see. 
I didn't test it on Termux before. seems like it is a bug of watchdog.
I'll look into it.
